name: tic_tac_toe
description: "A new Flutter project."
publish_to: 'none'

version: 3.0.6

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts:
  fluttertoast: ^8.2.4
  google_mobile_ads:
  audioplayers:
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/