name: tic_tac_toe
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  google_fonts:
  fluttertoast: ^8.2.4
  google_mobile_ads:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/